version: '3.9'

services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
      - "../SSL/Explorer:/etc/explorer"
      - "../SSL/Stats:/etc/stats"
      - "../SSL/Visual:/etc/visual"
      - "../SSL/RPC:/etc/rpc"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - target: 8090
        published: 8090
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
      - target: 8085
        published: 8085
      - target: 443
        published: 443
